linters:
  disable-all: true
  enable:
    # for more info, run -> golangci-lint help linters
    # to enable all, run -> golangci-lint run --enable-all
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - depguard
    - dogsled
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godox
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    - scopelint
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - wsl
    - dupl

    # potentially enable in the future
    # - gocognit
    # - gocyclo

    # useless
    # - funlen
    # - gosec

run:
linters-settings:
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0
  govet:
    # report about shadowed variables
    check-shadowing: true
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, 
    # and can be changed with the tab-width option
    line-length: 80
    tab-width: 4

output:
  # print lines of code with issue
  print-issued-lines: false

service:
  # use the fixed version to not introduce new linters unexpectedly
  golangci-lint-version: 1.24.0
